export const preRegisterContactFormatter = (item) => {
  return {
    accountId: item?.accountId || null,
    citizenId: item?.citizenId || '',
    id: item?.preregistorId || 0,
    consentStatus: item?.consentStatus || null,
    titleName: item?.titleName || '',
    firstname: item?.firstname || '',
    lastname: item?.lastname || '',
    companyName: item?.companyName || '',
    mobile: item?.mobile || '',
    email: item?.email || '',
    positionName: item?.positionName || '',
    personName: item?.personName || '',
    startDate: item?.startDate || '',
    expireDate: item?.expireDate || '',
    peregistorTimeStart: item?.peregistorTimeStart || '',
    peregistorTimeEnd: item?.peregistorTimeEnd || '',
    image: item?.image || '',
    areaZoneId: item?.areaZoneId,
    areaZoneName: item?.areaZoneName || '',
    objectiveWorkId: item?.objectiveWorkId,
    objectiveWorkName: item?.objectiveWorkName || '',
    detailPreregistor: item?.detailPreregistor || '',
    shipPreregistorFollow: item?.shipPreregistorFollow || [],
    shipPreregistorMoc: item?.shipPreregistorMoc || [],
    shipUserarea: item?.shipUserarea || [],
    factoryDatabaseStatus: item?.factoryDatabaseStatus || false,
    employeeApprover: item?.employeeApprover || '',
    agencyApprover: item?.agencyApprover || '',
    mobileApprover: item?.mobileApprover || '',
    emailApprover: item?.emailApprover || '',
    employeeApproverFullName: 'SupervisorShipTest',
    shipStatusOperation: item?.shipStatusOperation || null,
    vehicleCar: item?.vehicleCar || null,
    vehicleItem: item?.vehicleItem || null,
    status: item?.status || null,
    subareazoneid: item?.subareazoneid || null,
    subareazonename: item?.subareazonename || null,
  }
}
